name: Push Docker Image and build

on:
  push:
    tags:
      - "dev-*"
      - "prod-*"

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    environment: docker
    outputs:
      tag: ${{ steps.extract_tag.outputs.TAG }}
    steps:
      - name: Check Docker version
        run: |
          docker --version
          docker info
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env from secret (DEV)
        if: startsWith(github.ref, 'refs/tags/dev-')
        run: echo "${{ secrets.ENV_LOCAL }}" > .env.local

      - name: Create .env from secret(PROD)
        if: startsWith(github.ref, 'refs/tags/prod-')
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag version
        id: extract_tag
        run: |
          echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build and push (dev)
        if: startsWith(github.ref, 'refs/tags/dev-')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile.dev
          push: true
          tags: |
            ksc036/blog-frontend:${{ env.TAG }}

      - name: Build and push (prod)
        if: startsWith(github.ref, 'refs/tags/prod-')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile.prod
          push: true
          tags: |
            ksc036/blog-frontend:${{ env.TAG }}

  gitops-update:
    runs-on: ubuntu-latest
    environment: git
    needs: docker-build-and-push
    outputs:
      dir: ${{ steps.set-envdir.outputs.env_dir }}
    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v3
        with:
          repository: ksc036/gitops-repo
          token: ${{ secrets.GITOPS_TOKEN }}
      - name: Set Variables from Tag
        id: set-envdir
        env:
          GIT_TAG: ${{ needs.docker-build-and-push.outputs.tag }}
        run: |
          if [[ "$GIT_TAG" =~ ^dev-v ]]; then
            echo "ENV_DIR=dev" >> $GITHUB_ENV
            echo "env_dir=dev" >> $GITHUB_OUTPUT
            echo "APP_VERSION=${GIT_TAG#dev-}" >> $GITHUB_ENV
          elif [[ "${GIT_TAG}" =~ ^prod-v* ]]; then
            echo "ENV_DIR=prod" >> $GITHUB_ENV
            echo "env_dir=prod" >> $GITHUB_OUTPUT
            echo "APP_VERSION=${GIT_TAG#prod-}" >> $GITHUB_ENV
          else
            echo "Invalid tag format"; exit 1
          fi

      - name: Update values.yaml
        env:
          GIT_TAG: ${{ needs.docker-build-and-push.outputs.tag }}
        run: |
          sed -i "s/\(image: .*:\).*/\1${GIT_TAG}/" namespaces/${ENV_DIR}/blog/fe/deployment.yaml

      - name: Commit and Push to GitOps Repo
        env:
          GIT_TAG: ${{ needs.docker-build-and-push.outputs.tag }}
        run: |
          git config user.name "github-actions"
          git config user.email "ksc036@gmail.com"
          git commit -am "Update ${ENV_DIR} blog fe to ${GIT_TAG}"
          git push
  argocd-deploy:
    runs-on: ubuntu-latest
    needs: gitops-update
    environment: argocd
    steps:
      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/download/v2.14.9/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Login to Argo CD
        run: |
          argocd version --client
          argocd login argocd.ksc036.store \
            --username ${{ secrets.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --grpc-web

      - name: Sync application
        run: |
          echo "ENV_DIR is ${{ needs.gitops-update.outputs.dir }}"
          argocd app sync argocd/${{ needs.gitops-update.outputs.dir }}-app \
